# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

{{- if (eq .Values.global.installationMode "multiClusterReceiver") }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-remote-write
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: gateway-default
      namespace: {{ .Release.Namespace }}
  {{- with .Values.prometheusCustomizations.http.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/api/v1/write"
      backendRefs:
        - name: openchoreo-observability-prometheus
          port: 9091
{{- end }}
