{{- if .Values.openSearchCluster.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    {{- range .Values.openSearchCluster.tlsRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  parentRefs:
    - name: gateway-default
      namespace: {{ .Release.Namespace }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: opensearch
          port: 9200
{{- end }}
