{{- if .Values.setup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-setup
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudwatch-setup
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
{{- end }}
