{{- if .Values.adapter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: logs-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    app: logs-adapter-cloudwatch
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.adapter.service.port }}
      targetPort: {{ .Values.adapter.service.port }}
      protocol: TCP
      name: http
  selector:
    app: logs-adapter-cloudwatch
{{- end }}
