# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

{{- if ne .Values.global.installationMode "multiClusterExporter" }}
apiVersion: v1
kind: Service
metadata:
  name: metrics-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    app: metrics-adapter-prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9099
    targetPort: 9099
    protocol: TCP
    name: http
  selector:
    app: metrics-adapter-prometheus
{{- end }}
