{{- if and .Values.adapter.enabled .Values.adapter.alerting.webhookIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-adapter-cloudwatch-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: metrics-adapter-cloudwatch
  {{- with .Values.adapter.alerting.webhookIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.adapter.alerting.webhookIngress.className | quote }}
  tls:
    - hosts:
        - {{ .Values.adapter.alerting.webhookIngress.host | quote }}
      secretName: {{ .Values.adapter.alerting.webhookIngress.tls.secretName | quote }}
  rules:
    - host: {{ .Values.adapter.alerting.webhookIngress.host | quote }}
      http:
        paths:
          - path: /api/v1alpha1/alerts/webhook
            pathType: Exact
            backend:
              service:
                name: metrics-adapter
                port:
                  number: {{ .Values.adapter.service.port }}
{{- end }}
